# Use root/example as user/password credentials
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    # (this is just an example, not intended to be a production configuration)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"